server:
  port: 8083

spring:
  application:
    name: forensics-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Configuration for the Python Sidecar
python:
  sidecar:
    url: http://localhost:8000
